import { createClient } from "@libsql/client";
import path from "path";
import { fileURLToPath } from "url";
import logger from "../logger.js";

const log = logger.child({ component: "DB" });

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const db = createClient({
  url: `file:${path.join(__dirname, "interview.db")}`,
});

export async function initDb() {
  await db.executeMultiple(`
    CREATE TABLE IF NOT EXISTS sessions (
      id TEXT PRIMARY KEY,
      created_at INTEGER DEFAULT (unixepoch()),
      candidate_name TEXT,
      jd_text TEXT,
      resume_text TEXT,
      jd_summary TEXT,
      resume_summary TEXT,
      difficulty TEXT DEFAULT 'mid',
      status TEXT DEFAULT 'setup',
      question_bank TEXT,
      current_question_index INTEGER DEFAULT 0,
      total_questions INTEGER DEFAULT 0,
      last_was_followup INTEGER DEFAULT 0,
      followup_count INTEGER DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS answers (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      question_index INTEGER NOT NULL,
      question TEXT NOT NULL,
      question_category TEXT,
      transcript TEXT,
      score_technical INTEGER,
      score_communication INTEGER,
      score_depth INTEGER,
      flags TEXT,
      analysis TEXT,
      created_at INTEGER DEFAULT (unixepoch())
    );

    CREATE TABLE IF NOT EXISTS reports (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT UNIQUE NOT NULL,
      overall_score INTEGER,
      technical_score INTEGER,
      communication_score INTEGER,
      problem_solving_score INTEGER,
      culture_fit_score INTEGER,
      strengths TEXT,
      gaps TEXT,
      red_flags TEXT,
      recommendation TEXT,
      narrative TEXT,
      created_at INTEGER DEFAULT (unixepoch())
    );
  `);

  // Add columns to existing DBs created before this schema version
  const sessionCols = [
    "last_was_followup INTEGER DEFAULT 0",
    "followup_count INTEGER DEFAULT 0",
    "agent_history TEXT",
    "agent_observations TEXT",
    "concluded_early INTEGER DEFAULT 0",
    "trace TEXT",
  ];
  for (const col of sessionCols) {
    const name = col.split(" ")[0];
    try {
      await db.execute(`ALTER TABLE sessions ADD COLUMN ${col}`);
      log.info({ column: `sessions.${name}` }, "DB migrated");
    } catch (_) { /* column already exists — fine */ }
  }

  // answers table — fields returned by analyseAnswer but previously not persisted
  const answerCols = [
    "overall_score INTEGER",
    "strength_points TEXT",
    "gap_points TEXT",
  ];
  for (const col of answerCols) {
    const name = col.split(" ")[0];
    try {
      await db.execute(`ALTER TABLE answers ADD COLUMN ${col}`);
      log.info({ column: `answers.${name}` }, "DB migrated");
    } catch (_) { /* column already exists — fine */ }
  }

  // reports table — fields generated by LLM but previously not persisted
  const reportCols = [
    "headline TEXT",
    "confidence TEXT",
    "skill_ratings TEXT",
    "suggested_next_steps TEXT",
  ];
  for (const col of reportCols) {
    const name = col.split(" ")[0];
    try {
      await db.execute(`ALTER TABLE reports ADD COLUMN ${col}`);
      log.info({ column: `reports.${name}` }, "DB migrated");
    } catch (_) { /* column already exists — fine */ }
  }

  log.info("DB initialised");
}

export default db;
